# Generated by Django 3.2.7 on 2021-09-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
